# Generated by Django 4.2.2 on 2023-07-20 04:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_memo_posted_at_task_memo_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='memo_posted_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='memo_text',
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_text', models.TextField()),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='todo.task')),
            ],
        ),
    ]
